---
name: Eden
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [master]

jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
      - name: setup
        run: |
          sudo apt update
          sudo apt install -y qemu-utils qemu-system-x86
      - name: host info
        run: |
          ip a
      - name: get eden
        uses: actions/checkout@v2
      - name: build eden
        run: |
          echo "::error file=adam/Makefile,line=1,col=1::Something went wrong GH"
          exit 1
